import Image from "next/image";
import Link from "next/link";
import { FaArrowLeftLong } from "react-icons/fa6";


// export const metadata = {
//   title: "Dragon News - Category-Details",
//   description: "Generated by create next app",
// };

export const generateMetadata =async ({params}) => {
     const { id } = await params;
    const res = await fetch(`https://openapi.programming-hero.com/api/news/${id}`);
    const newsDetails = await res.json();
    const data = newsDetails.data[0];
    return {
        title: data.title, 
        description: data.details
    }
 }


const NewsDetailsPage = async ({ params }) => {
    const { id } = await params;
    const res = await fetch(`https://openapi.programming-hero.com/api/news/${id}`);
    const newsDetails = await res.json();
    const data = newsDetails.data[0];
    console.log("hime , ", data.length);
    return (
        <div className="max-w-[100vh] mx-auto">
            <p>Dragon News</p>
            <div className="max-w-[100vh] mx-auto">
                <div className="col-span-9 shadow p-9 my-2 space-y-4">
                    <Image src={data.image_url} alt="img " height={300} width={300} className="w-full"></Image>
                    <h2 className="text-2xl font-bold">{data.title}</h2>
                    <p className="text-[#706F6F]">{data.details}</p>
                    <Link href={`/category/${data.category_id}`}>
                        <button className="flex items-center gap-1 text-white bg-red-600 p-3 rounded-xl">
                            <FaArrowLeftLong /><p>All news in this category</p>
                        </button>
                    </Link>
                </div>
                
            </div>
        </div>
    );
};

export default NewsDetailsPage;