
export const metadata = {
  title: "Dragon News - about us",
  description: "Generated by create next app",
};


const AboutPage = () => {
    return (
        <div>
            This is about page
        </div>
    );
};

export default AboutPage;