"use client";

import { authClient } from "@/lib/auth-client";
import Link from "next/link";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { FaEye } from "react-icons/fa6";

// export const metadata = {
//   title: "Dragon News- password ",
//   description: "Generated by create next app",
// };

const LoaginPage = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
  } = useForm();

  const [isShowPassword, setIsShowPassword] = useState(false);

  const handelLoginForm = async (data) => {
    //   console.log(data, "   hima");
    const { email, password } = data;
    const { data: res, error } = await authClient.signIn.email({
      email: email, // required
      password: password, // required
      rememberMe: true,
      callbackURL: "/",
    });
    if (error) {
      alert("Your Account Alreay Exis");
    } else {
      alert("Login SuccessFully");
    }
  };

  console.log(watch("email"));

  return (
    <div className="container mx-auto min-h-[80vh] flex justify-center items-center bg-slate-100">
      <div className="p-4 rounded-xl bg-white">
        <h2 className="font-bold text-3xl text-center mb-3">
          Login Your Account{" "}
        </h2>

        <form className="space-y-3" onSubmit={handleSubmit(handelLoginForm)}>
          <fieldset className="fieldset">
            <legend className="fieldset-legend">Email</legend>
            <input
              {...register("email", { required: "Email field is required" })}
              type="email"
              className="input"
              placeholder="Enter Your Email"
            />
            {errors.email && (
              <p className="text-red-500">{errors.email.message}</p>
            )}
          </fieldset>

          <fieldset className="fieldset ">
            <legend className="fieldset-legend">Password</legend>
            <input
              {...register("password", {
                required: "Password field is required",
              })}
              type={isShowPassword ? "text" : "password"}
              className="input"
              placeholder="Enter Your Password"
            />
            <span
              className=""
              onClick={() => setIsShowPassword(!isShowPassword)}
            >
              <FaEye></FaEye>
            </span>
            {errors.password && (
              <p className="text-red-500">{errors.password.message}</p>
            )}
          </fieldset>

          <button className="btn w-full bg-slate-800 text-white">Login</button>
        </form>

        <p className="text-center mt-3 text-xs">
          Dont’t Have An Account ?{" "}
          <Link href="/register" className="text-red-700">
            Register
          </Link>
        </p>
      </div>
    </div>
  );
};

export default LoaginPage;
