export const metadata = {
  title: "Dragon News - Career",
  description: "Generated by create next app",
};


const CarrerPage = () => {
    return (
        <div>
            This is Career Page
        </div>
    );
};

export default CarrerPage;